server:
  port: 8608
  servlet:
    context-path: /simpleservice

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/simpleservicedb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: User@12345
  redis:
    host: 127.0.0.1
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 36
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        #连接池中的最大空闲连接
        max-idle: 8
        min-idle: 4
  thymeleaf:
    encoding: UTF-8

logging:
  level:
    com.lyt.simpleservice.mybatis.service: debug

mybatis:
  mapperLocations: classpath:mybatis/mysql/*Mapper.xml
  typeAliasesPackage: com.lyt.simpleservice.mybatis.domain

simpleservice:
  redis:
    name: simpleservicerdb
