server:
  port: 8608
  servlet:
    context-path: /simpleservice
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/simpleservicedb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: User@12345
  thymeleaf:
    encoding: UTF-8
logging:
  level:
    com.lyt.simpleservice.mybatis.dao: debug

mybatis:
  mapperLocations: classpath:mybatis/mysql/*Mapper.xml
  typeAliasesPackage: com.lyt.simpleservice.mybatis.domain